server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://zyurfsbznnopfx:819807c6a93636292047ea919527180a35cc3b4edfa826664dd7df6df8a890f6@ec2-54-87-112-29.compute-1.amazonaws.com:5432/db37i0hch2vf2h
    username: zyurfsbznnopfx
    password: 819807c6a93636292047ea919527180a35cc3b4edfa826664dd7df6df8a890f6
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander